public enum ResultTypeEnum
{
    Success,
    InsufficientCash,
    OrderHasNoBuyer,
    OrderHasNoGood,
    OrderHasInvalidPrice,
    OrderHasInvalidQuantity,
    ContextHasNoTrade,
    OrderHasNoSeller,
    MarketNotSet,
    SpreadHasNoBid,
    SpreadHasNoAsk,
    SpreadHasNoGood,
    DuplicateOrder,
    SelfTrade,
    NoSupplierForGood,
    NoMatchingCounterParties,
    PartialFill,
    OrderHasNoSubmittingCompany,
    InsufficientFunds,
    InsufficientGoods
}